### ISSUE TITLE
Start/Stop implementation

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#67]
Don't know if this is going to be a requirement this year or not, but we should be ready for it.
Previously, parks and rec demanded that we turn off the sculpture for five minutes out of every twenty to discourage people from gathering (Covid). 

We need to make sure this functionality still works in the current sculpture.

**Comment by mcslee** [comment]
Would be very easily implemented as a custom modulator applied to master output brightness fader, just runs a 20 minute loop. I'm not going to implement this, and honestly if SF still doesn't want people gathering outdoors at this point after we've propositioned everyone to keep JFK open for walking...

Very easy job if it comes up, just give me a shout if that does happen and you want a hand with it.

**Comment by cswales** [comment]
We've got existing code - there are config params, there is a loop task, it should run. Maybe we just punt on testing it in favor of adding the master output fader if and when we need it. Less code is always better.

**Comment by bbulkow** [comment]
Charlie has stated we don't need this, and it's a bunch of complexity we don't want to add.

I could see that since the platform is taking on the capabilities of doing playback, I would expect there should be methods accessible to the plugin which would specify the file and start and stop and record, giving the plugin full control. This would allow us true external control for doing things like uploading a pattern file remotely and switch to it.
