### ISSUE TITLE
Hook up masterbrightness correctly

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#75]
Both the iPad and the APC40 are supposed to be able to control the brightness. In the original code, there was a brightness effect, and a brightness effect parameter. The Midi code got passed the parameter, and the iPad controller operated on the effect directly.

Now the APC40 does brightness i don't know how, the iPad manipulates a brightness control that isn't actually hooked up to something, and the Entwined plugin creates a brightness control, hooks it up, and then abandons it.

There's also something similar going on with autoplayBrightness, except that I really don't understand how that one is supposed to work and interact with masterBrightness

**Comment by bbulkow** [comment]
The way the APC40 works is that there is a "control surface" defined, and under the covers, the master brightness is getting mapped by default to that knob on the APC40.

I believe there should be a well known name (OSC name) for the master brightness, which one can get by hovering over it, then probably you can attach to the parameter by that name in code, then read-write it all one wants.

@mcslee  ? is my answer correct?

**Comment by mcslee** [comment]
The APC40 will directly wire itself up to `this.lx.engine.output.brightness` which is the master output fader. Note that this is *direct* control, not modulation. So these changes will overwrite any other value.

Per the other issue you opened @bbulkow - this will not impact the visual UI. It only scales the brightness of network output packets.

If you want other things additionally controlling brightness, you have a couple options:
- Use modulation so that the secondary brightness changes on the master fader stack on top of the APC40 setting
- Put an effect on the master bus that scales brightness and have the iPad/whatever control that - note that this will also impact the brightness visible on the UI
