### ISSUE TITLE
Shutdown ... or not

### ISSUE THREAD

**Issue by cswales** [squaredproject/Entwined#79]
When clicking on the close box (Mac), the application leaves the screen and issues a 'thanks for playing' message, but the application does not terminate. Have to ctrl-C

**Comment by mcslee** [comment]
The `Entwined` plugin class needs to override the `public void dispose()` method and terminate the server threads here. What's happening now is the application shuts down all its scaffolding, but the JVM doesn't quit because there are still running non-daemon threads. I don't want to have LX force kill them in case they're doing something important.

The `dispose()` method is where you can clean that up yourself.

**Comment by cswales** [comment]
Okay, so this is pretty much done in a checkin to my branch.
